---
# tasks file for lamp
- name: Install nginx,isc-dhcp-server
  ansible.builtin.package:
      name: "{{ packages }}"
      state: present
      
- name: Start service nginx,isc-dhcp-server
  ansible.builtin.service:
      name: "{{ services[0] }}"
      state: started
      enabled: yes

- name: Start service nginx,isc-dhcp-server
  ansible.builtin.service:
      name: "{{ services[1] }}"
      state: started
      enabled: yes
  register: service_results
  failed_when: false  

- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /root/ansible/index.html
    dest: /var/www/html/
  ignore_errors: True
 
  
- name: Allow everything and enable UFW
  community.general.ufw:
    state: enabled
    policy: allow
  
- name: Copy file with owner and permissions
  ansible.builtin.copy:
    src: /etc/dhcp/dhcpd.conf
    dest: /etc/dhcp/dhcpd.conf

- name: create Update
  command: dnf update -y
  register: command_failed
  failed_when: command_failed.rc == 0